theme: jekyll-theme-minimal
title: NES Emulator Development Blog
logo: /assets/img/smb_grid.png
description: Bookmark this to keep an eye on my project updates!
google_analytics:
github:
  is_project_page: false
